-define(BACKLOG_SIZE, 1024).
-define(CLIENT_SSL, arithmetic_ssl_client).
-define(CLIENT_TCP, arithmetic_tcp_client).
-define(CLIENT_UDP, arithmetic_udp_client).
-define(POOL_NAME, arithmetic).
-define(POOL_SIZE, 16).
-define(PORT, 62169).
-define(TIMEOUT, 500).
