name: Erlang CI
on: [push]
jobs:
  build:
    runs-on:
      group: SelfHostedDefault
      labels: ubuntu-22.04-large
    strategy:
      matrix:
        erlang: [28, 29]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run:  make compile
    - name: Lint
      run:  make lint
    - name: Run xref
      run:  make xref
    - name: Run dialyzer
      run:  make dialyzer
    - name: Run eunit
      run:  make eunit
